### PR TITLE
Added D16XCEL PanelVersionUpdate and associated test

### PR DESCRIPTION
**Pull request by ozadr1an**
Closes https://github.com/nickw444/nessclient/issues/66

### CODE REVIEW

**Comment by ozadr1an** [comment]
Updated to support D16XCEL in both PanelVersionUpdate and also the associated tests

**Review by nickw444 — APPROVED** [review]
Looks good to me, you don't happen to have access to the serial comms protocol that documents this panel version? Would be a useful resource for further development of this library,

**Comment by ozadr1an** [comment]
> Looks good to me, you don't happen to have access to the serial comms protocol that documents this panel version? Would be a useful resource for further development of this library,

I reached out to Ness about that... they're pretty good, but their answer was not a lot had changed at all other than the version numbers... I'll pass on what I have otherwise.

**Comment by ozadr1an** [comment]
Also - random question. How long does it take for this to usual turnup upstream ? Every update I have to hand patch again :)

**Comment by nickw444** [comment]
> Also - random question. How long does it take for this to usual turnup upstream ? Every update I have to hand patch again :)

The dependency needs to be upgraded within the Home Assistant repo for the new version to be picked up: https://github.com/home-assistant/core/blob/dev/homeassistant/components/ness_alarm/manifest.json#L8

I'm a code owner of the ness alarm component over there, so happy to approve a PR that you raise to upgrade it.

**Comment by ozadr1an** [comment]
Just going through and getting a dev environment setup for HA so I can tick yes to all the checkboxes instead of just updating the manifest file lol. 

BTW.. Ness pointed me at this ASCII Protocol guide. Its from 2019 though, and doesn't have the newer version types in it:
https://drive.google.com/file/d/1vl8Gs1GY-gKAPSiU8yjCzrgQxm8ybhQh/view?usp=sharing

**Pull request merged**
